### ISSUE TITLE
Reproducing MELS data from message stream

### ISSUE THREAD

**Issue by lczyk** [elexon-data/iris-clients#21] opened 2024-03-14 15:23 UTC
I'm having issues reproducing some of the data which available through your website. There are a couple of cases but the simplest one i'd like to ask about is MELS for E_LYNE1 between the times 14/03/24 01:00 -> 02:00. The data from your website can be seen [here](https://bmrs.elexon.co.uk/balancing-mechanism-bmu-view?bmuId=E_LYNE1&activeTab=Physical&startDate=2024-03-14T01%3A00%3A00.000Z&endDate=2024-03-14T02%3A00%3A00.000Z) (also see screenshot below) and the relevant records I've received are attached below.

How does the data on the website follow from these records? If there is any documentation you could point me to which explains the process of "stitching" together MELS I would be very grateful.

### MELS on elexon website:

<img width="735" alt="Screenshot 2024-03-14 at 14 18 50" src="https://github.com/elexon-data/iris-clients/assets/24707398/5aa43598-d76f-4db3-95a7-49a789a2094c">

### MELS data as put together from the messages

![plot_8](https://github.com/elexon-data/iris-clients/assets/24707398/570890db-4f9c-4dc7-ae03-939650fb8544)

### animation

![animate](https://github.com/elexon-data/iris-clients/assets/24707398/6bcb83a5-1b2f-4843-87a3-4e5ed0812537)

## records

[E_LYNE1_MELS.json](https://github.com/elexon-data/iris-clients/files/14634744/messages.json)

**Comment by rit-bit** [comment] 2024-04-09 16:05
Hi @MarcinKonowalczyk, thanks for raising this issue. We are currently looking into it and will update this issue when we have more information

**Comment by rit-bit** [comment] 2024-04-23 10:03
Latest update:

Thank you @MarcinKonowalczyk for identifying an edge case which occurs when redeclarations are submitted where both of the following are true:
- the redeclaration spans across multiple settlement periods
- levelFrom and levelTo are different

On the second point, our logic assumes this doesn't happen because the extrapolation between the two levels would be ambiguous. The extra spike in the example above is caused by splitting at the settlement period boundaries (which is necessary for the sequencing calculations) since we assume levelFrom and levelTo have the same value.

The data submitted has not matched our assumptions, and Elexon is looking into why this is the case. In the meantime we will not change the way we process MILS/MELS data until we receive clarification, so I'm closing this issue.

**Closed as not planned by rit-bit** 2024-04-23 10:03 UTC
